name: "Delete BBD"

on:
  delete:
    branches:
      # Ignore tags
      - "**"
  pull_request:
    types: [ closed ]

permissions:
  id-token: write
  contents: read

concurrency:
  group: delete-bbd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  delete-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: Branch delete no PR only
        if: github.event_name == 'pull_request' || steps.PR.outputs.pr_found == 'false'
        run: echo "done"
