name: "Delete BBD"

on:
  - delete
  - workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  delete-deploy:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Delete
        run: git checkout -b $GITHUB_HEAD_REF  # required, on pull_request event github action works on dangling commit
